### ISSUE TITLE
Status: 500 Internal Server Error

### ISSUE THREAD

**Issue by mickdeery** [olafloogman/functions-dotnet-liquidtransform#1]
I've got the function working locally but after I deploy it to Azure it gives me a " Status: 500 Internal Server Error". No log information is displayed. This is testing in the portal and from postman.
Any ideas?
Great job on this code by the way!

**Comment by olafloogman** [comment]
Cheers Mick. Happy to help you out here. Does the raw HTTP reponse not output any further details? I'll need to address the issue of a lack of diagnostics, but in the meantime you could perhaps integrate your Azure Function with Application Insights for better visibility.
Also, if you navigate to your Function App -> Platform Features you'll find an option 'Log streaming' this will dump any exceptions that occur whilst you call the API, give this a try do some some diagnosis.
Lastly, did you create a container 'liquid-transforms' in the storage account associated with your function, and upload your Liquid template?

**Comment by mickdeery** [comment]
I can't see logs, errors, anything in the log streaming or app insights. Yes I've created the blob container 'liquid-transforms' in the storage account that my function app resides.

![image](https://user-images.githubusercontent.com/32499028/53538987-df8ef580-3b63-11e9-83c4-f6c72aff538c.png)

Many thanks

**Comment by olafloogman** [comment]
Thanks Mick, can you provide me with the raw HTTP from postman? I'm working on improved error handling in the meantime, I'll keep you posted in progress.

**Comment by mickdeery** [comment]
POST /api/liquidtransformer/crm-eds-opportunity.liquid?code=********ZT/PFVuevIAnVeJ9PzF2XTCWZUMmfRWlCcom8Nmy0ZaEIA== HTTP/1.1
Host: server.azurewebsites.net
Content-Type: application/json
Accept: application/xml
cache-control: no-cache
Postman-Token: b77cd79b-add1-4c0f-a6d0-51664edad532
{
	"name": "olaf"
}------WebKitFormBoundary7MA4YWxkTrZu0gW--

**Comment by olafloogman** [comment]
Sorry, I meant the HTTP response

**Comment by mickdeery** [comment]
Server →Microsoft-IIS/10.0
X-Powered-By →ASP.NET
Date →Thu, 28 Feb 2019 03:36:18 GMT
Content-Length →0

**Comment by olafloogman** [comment]
Thanks Mick, 
I'm not quite sure why your logging console doesn't show anything. I've added error handling to the code, so please pull the latest bits and let me know how you go.

**Comment by olafloogman** [comment]
Hi Mick, have you had a chance to test the changes?

**Comment by mdeery** [comment]
Hi, not yet. I'm still trying to work out why I don't get log streaming for this function app.

**Comment by mdeery** [comment]
Solved! My function app was missing an application setting "FUNCTIONS_EXTENSION_VERSION" with value "~1".
